import { LakeMetadata } from '../src/types.js';

export interface PredefinedLake {
  metadata: LakeMetadata;
  // Relative lake center and shape parameters
  shape: {
    type: 'kettle' | 'complex_bays' | 'reservoir' | 'elongated';
    customSdfId?: string;
    aspectRatio: number; // width / height
    lakeRadiusRatio: number; // relative size in bounding box (0.1 - 0.5)
    rotationDeg: number;
    bays?: Array<{ angleDeg: number; distance: number; radius: number; depthMult: number }>;
    islands?: Array<{ x: number; y: number; radius: number }>;
    deepestPointOffset: { x: number; y: number }; // normalized -1 to 1 relative to center
    shorelineRoughness: number;
  };
  terrainProfile: {
    moraineHeightM: number;
    roughness: number;
    surroundingSlope: 'gentle_rolling' | 'steep_bluffs' | 'glacial_till' | 'karst_hills';
  };
}

export const MIDWESTERN_LAKES: PredefinedLake[] = [
  {
    metadata: {
      id: 'deam-lake-in',
      name: 'Deam Lake',
      state: 'Indiana',
      county: 'Clark County',
      lat: 38.4633,
      lon: -85.8672,
      surfaceElevationM: 161,
      surfaceElevationFt: 528,
      maxDepthM: 9.14,
      maxDepthFt: 30.0,
      meanDepthM: 4.57,
      meanDepthFt: 15.0,
      areaAcres: 194,
      perimeterKm: 5.8,
      geologicalOrigin: 'Impounded reservoir formed by damming Stone Branch in the unglaciated Knobstone Escarpment',
      description: 'Accurately modeled from DNR bathymetric survey: features the long winding Stone Branch north channel, northwest arm, western boat ramp cove, branching eastern antler bays, deep 30-ft south basin depression, and south dam along Deam Lake Road.',
      bounds: {
        minLat: 38.455,
        maxLat: 38.474,
        minLon: -85.877,
        maxLon: -85.856,
      },
      contourIntervalFt: 5,
      generationMethod: 'curated-survey',
      topoAnalysisNotes: 'Survey contours synthesized directly from the Indiana Department of Natural Resources (DNR) Division of Fish & Wildlife Bathymetric Map and USGS 7.5-minute Speed/Henryville quadrangles. Resolves the 30.0 ft south basin hole, littoral feeder flats, Stone Branch stream channel, and 180+ ft forested Knobstone ridges.',
      sources: [
        {
          title: 'Indiana DNR Division of Fish & Wildlife - Deam Lake Hydrographic Survey',
          uri: 'https://www.in.gov/dnr/fish-and-wildlife/',
          sourceType: 'dnr_survey',
          snippet: 'Official Indiana DNR 5-ft bathymetric contour survey identifying 30-ft maximum depth, boat ramp channel, and shoreline structure.'
        },
        {
          title: 'USGS National Map & Speed, IN 7.5-minute Topographic Quadrangle',
          uri: 'https://www.usgs.gov/programs/national-geospatial-program/national-map',
          sourceType: 'usgs_topo',
          snippet: 'Topographic contour elevation mapping depicting Stone Branch creek drainage and the unglaciated Knobstone Escarpment bluffs.'
        },
        {
          title: 'Clark State Forest Geological & Reservoir Impoundment Survey',
          uri: 'https://www.in.gov/dnr/forestry/',
          sourceType: 'hydrographic_database',
          snippet: 'Earthen dam embankment specifications along Deam Lake Road with spillway gradient drop.'
        }
      ],
      topoFeatures: [
        { label: '30-ft Deep Hole', type: 'deep_hole', normX: 0.08, normY: 0.36, depthOrElevFt: 30.0, description: 'Deepest soundings depression (30.0 ft / 9.1 m) in south basin' },
        { label: 'Earthen Dam Embankment', type: 'dam', normX: -0.28, normY: 0.58, depthOrElevFt: 532, description: '1,100-ft earthen dam impounding Stone Branch along Deam Lake Road' },
        { label: 'Stone Branch North Inlet', type: 'inlet', normX: 0.32, normY: -0.84, depthOrElevFt: 2.0, description: 'Primary northern feeder creek entering from forested hills' },
        { label: 'Northwest Feeder Arm', type: 'cove', normX: -0.58, normY: -0.42, depthOrElevFt: 4.5, description: 'Secondary winding feeder branch and shallow cove' },
        { label: 'West Public Boat Ramp', type: 'boat_ramp', normX: -0.36, normY: 0.10, depthOrElevFt: 6.0, description: 'Concrete launch bay and access pier' },
        { label: 'East Antler Bays', type: 'cove', normX: 0.58, normY: -0.05, depthOrElevFt: 8.0, description: 'Dual branching bays formed by submerged ridge spurs' },
        { label: 'Knobstone Escarpment Ridge', type: 'ridge', normX: 0.65, normY: -0.60, depthOrElevFt: 710, description: 'Clark State Forest ridges rising 180+ ft above the water level' }
      ]
    },
    shape: {
      type: 'reservoir',
      customSdfId: 'deam-lake',
      aspectRatio: 1.15,
      lakeRadiusRatio: 0.42,
      rotationDeg: 0,
      deepestPointOffset: { x: 0.08, y: 0.36 },
      shorelineRoughness: 0.04,
    },
    terrainProfile: {
      moraineHeightM: 52,
      roughness: 0.65,
      surroundingSlope: 'steep_bluffs',
    },
  },
  {
    metadata: {
      id: 'beals-lake-in',
      name: 'Beals Lake',
      state: 'Indiana',
      county: 'Steuben County',
      lat: 41.5385,
      lon: -85.0842,
      surfaceElevationM: 298,
      surfaceElevationFt: 978,
      maxDepthM: 14.5,
      maxDepthFt: 47.6,
      meanDepthM: 6.2,
      meanDepthFt: 20.3,
      areaAcres: 124,
      perimeterKm: 3.8,
      geologicalOrigin: 'Glacial kettle lake formed by isolated ice block depression during Wisconsin glaciation',
      description: 'A classic northeastern Indiana kettle lake nestled within hummocky glacial moraine topography with natural sand bars, submerged weed beds, and steep glacial drop-offs.',
      bounds: {
        minLat: 41.528,
        maxLat: 41.549,
        minLon: -85.099,
        maxLon: -85.069,
      },
    },
    shape: {
      type: 'kettle',
      aspectRatio: 1.15,
      lakeRadiusRatio: 0.38,
      rotationDeg: -25,
      bays: [
        { angleDeg: 45, distance: 0.32, radius: 0.18, depthMult: 0.65 },
        { angleDeg: 210, distance: 0.30, radius: 0.16, depthMult: 0.55 },
      ],
      deepestPointOffset: { x: 0.05, y: -0.08 },
      shorelineRoughness: 0.06,
    },
    terrainProfile: {
      moraineHeightM: 16,
      roughness: 0.45,
      surroundingSlope: 'glacial_till',
    },
  },
  {
    metadata: {
      id: 'lake-wawasee-in',
      name: 'Lake Wawasee',
      state: 'Indiana',
      county: 'Kosciusko County',
      lat: 41.4081,
      lon: -85.7042,
      surfaceElevationM: 262,
      surfaceElevationFt: 860,
      maxDepthM: 23.5,
      maxDepthFt: 77.1,
      meanDepthM: 6.7,
      meanDepthFt: 22.0,
      areaAcres: 3048,
      perimeterKm: 40.2,
      geologicalOrigin: 'Large glacial drift depression with complex underwater shoals, sandbars, and drumlin ridges',
      description: 'The largest natural inland lake in Indiana, boasting extensive shallow flats, sudden underwater drop-offs, multiple peninsulas, and Johnson Bay.',
      bounds: {
        minLat: 41.385,
        maxLat: 41.432,
        minLon: -85.745,
        maxLon: -85.660,
      },
    },
    shape: {
      type: 'complex_bays',
      aspectRatio: 1.45,
      lakeRadiusRatio: 0.42,
      rotationDeg: 35,
      bays: [
        { angleDeg: 30, distance: 0.45, radius: 0.22, depthMult: 0.7 },
        { angleDeg: 120, distance: 0.38, radius: 0.20, depthMult: 0.8 },
        { angleDeg: 260, distance: 0.40, radius: 0.24, depthMult: 0.9 },
      ],
      islands: [
        { x: -0.15, y: 0.1, radius: 0.05 },
      ],
      deepestPointOffset: { x: 0.12, y: 0.05 },
      shorelineRoughness: 0.09,
    },
    terrainProfile: {
      moraineHeightM: 22,
      roughness: 0.5,
      surroundingSlope: 'glacial_till',
    },
  },
  {
    metadata: {
      id: 'lake-monroe-in',
      name: 'Lake Monroe',
      state: 'Indiana',
      county: 'Monroe / Brown County',
      lat: 39.0250,
      lon: -86.4350,
      surfaceElevationM: 164,
      surfaceElevationFt: 538,
      maxDepthM: 18.3,
      maxDepthFt: 60.0,
      meanDepthM: 5.3,
      meanDepthFt: 17.4,
      areaAcres: 10750,
      perimeterKm: 177.0,
      geologicalOrigin: 'Impounded reservoir carving through unglaciated Mississippian limestone plateau and steep hollows',
      description: 'Indiana’s largest body of water, sprawling through the forested Norman Upland with steep wooded ridges, winding creek arms, and deep drowned river channels.',
      bounds: {
        minLat: 38.995,
        maxLat: 39.060,
        minLon: -86.485,
        maxLon: -86.385,
      },
    },
    shape: {
      type: 'reservoir',
      aspectRatio: 1.35,
      lakeRadiusRatio: 0.40,
      rotationDeg: 15,
      bays: [
        { angleDeg: 70, distance: 0.48, radius: 0.16, depthMult: 0.6 },
        { angleDeg: 170, distance: 0.42, radius: 0.19, depthMult: 0.75 },
        { angleDeg: 310, distance: 0.46, radius: 0.17, depthMult: 0.8 },
      ],
      deepestPointOffset: { x: -0.22, y: -0.05 },
      shorelineRoughness: 0.12,
    },
    terrainProfile: {
      moraineHeightM: 65,
      roughness: 0.65,
      surroundingSlope: 'steep_bluffs',
    },
  },
  {
    metadata: {
      id: 'devils-lake-wi',
      name: 'Devils Lake',
      state: 'Wisconsin',
      county: 'Sauk County',
      lat: 43.4215,
      lon: -89.7312,
      surfaceElevationM: 294,
      surfaceElevationFt: 965,
      maxDepthM: 14.3,
      maxDepthFt: 47.0,
      meanDepthM: 9.1,
      meanDepthFt: 30.0,
      areaAcres: 360,
      perimeterKm: 5.6,
      geologicalOrigin: 'Glacially dammed gorge carved through 1.6-billion-year-old Baraboo Quartzite',
      description: 'Dramatic geological marvel flanked by 500-foot sheer pink quartzite bluffs with massive boulder talus slopes dropping straight into crystalline waters.',
      bounds: {
        minLat: 43.405,
        maxLat: 43.438,
        minLon: -89.748,
        maxLon: -89.714,
      },
    },
    shape: {
      type: 'elongated',
      aspectRatio: 0.65,
      lakeRadiusRatio: 0.36,
      rotationDeg: 5,
      deepestPointOffset: { x: 0.0, y: 0.0 },
      shorelineRoughness: 0.05,
    },
    terrainProfile: {
      moraineHeightM: 135,
      roughness: 0.85,
      surroundingSlope: 'steep_bluffs',
    },
  },
  {
    metadata: {
      id: 'lake-mendota-wi',
      name: 'Lake Mendota',
      state: 'Wisconsin',
      county: 'Dane County',
      lat: 43.1040,
      lon: -89.4180,
      surfaceElevationM: 259,
      surfaceElevationFt: 850,
      maxDepthM: 25.3,
      maxDepthFt: 83.0,
      meanDepthM: 12.8,
      meanDepthFt: 42.0,
      areaAcres: 9781,
      perimeterKm: 34.4,
      geologicalOrigin: 'Glacial basin scooped by Green Bay Lobe of Laurentide Ice Sheet within pre-glacial river valley',
      description: 'The "most studied lake in the world" bordering Madison and UW-Madison, featuring Governor’s Island, Picnic Point spit, and deep central glacial trenches.',
      bounds: {
        minLat: 43.075,
        maxLat: 43.145,
        minLon: -89.475,
        maxLon: -89.360,
      },
    },
    shape: {
      type: 'complex_bays',
      aspectRatio: 1.25,
      lakeRadiusRatio: 0.44,
      rotationDeg: -10,
      bays: [
        { angleDeg: 140, distance: 0.38, radius: 0.18, depthMult: 0.6 },
        { angleDeg: 320, distance: 0.42, radius: 0.22, depthMult: 0.75 },
      ],
      deepestPointOffset: { x: 0.08, y: 0.02 },
      shorelineRoughness: 0.07,
    },
    terrainProfile: {
      moraineHeightM: 32,
      roughness: 0.45,
      surroundingSlope: 'glacial_till',
    },
  },
  {
    metadata: {
      id: 'torch-lake-mi',
      name: 'Torch Lake',
      state: 'Michigan',
      county: 'Antrim County',
      lat: 45.0200,
      lon: -85.3100,
      surfaceElevationM: 181,
      surfaceElevationFt: 594,
      maxDepthM: 93.0,
      maxDepthFt: 305.0,
      meanDepthM: 34.0,
      meanDepthFt: 111.0,
      areaAcres: 18770,
      perimeterKm: 65.8,
      geologicalOrigin: 'Deep glacial fjord carved by Grand Traverse ice lobe, Michigan’s second largest and deepest inland lake',
      description: 'Famous for its vivid turquoise shallows and abrupt drop into oceanic blue depths exceeding 300 feet, framed by towering glacial drumlins and sand bluffs.',
      bounds: {
        minLat: 44.920,
        maxLat: 45.130,
        minLon: -85.370,
        maxLon: -85.250,
      },
    },
    shape: {
      type: 'elongated',
      aspectRatio: 0.32,
      lakeRadiusRatio: 0.42,
      rotationDeg: -8,
      deepestPointOffset: { x: 0.0, y: 0.15 },
      shorelineRoughness: 0.04,
    },
    terrainProfile: {
      moraineHeightM: 85,
      roughness: 0.6,
      surroundingSlope: 'steep_bluffs',
    },
  },
  {
    metadata: {
      id: 'geneva-lake-wi',
      name: 'Geneva Lake',
      state: 'Wisconsin',
      county: 'Walworth County',
      lat: 42.5700,
      lon: -88.5000,
      surfaceElevationM: 263,
      surfaceElevationFt: 863,
      maxDepthM: 44.0,
      maxDepthFt: 144.0,
      meanDepthM: 18.6,
      meanDepthFt: 61.0,
      areaAcres: 5401,
      perimeterKm: 34.4,
      geologicalOrigin: 'Glacial channel lake formed where melting ice sheet left terminal moraine dams',
      description: 'Deep spring-fed lake with steep rolling moraine ridges, clear water, and deep sub-lacustrine trenches.',
      bounds: {
        minLat: 42.540,
        maxLat: 42.600,
        minLon: -88.580,
        maxLon: -88.420,
      },
    },
    shape: {
      type: 'elongated',
      aspectRatio: 1.8,
      lakeRadiusRatio: 0.40,
      rotationDeg: 12,
      deepestPointOffset: { x: -0.1, y: 0.0 },
      shorelineRoughness: 0.05,
    },
    terrainProfile: {
      moraineHeightM: 40,
      roughness: 0.5,
      surroundingSlope: 'glacial_till',
    },
  },
  {
    metadata: {
      id: 'lake-of-the-ozarks-mo',
      name: 'Lake of the Ozarks',
      state: 'Missouri',
      county: 'Camden / Miller County',
      lat: 38.2000,
      lon: -92.6200,
      surfaceElevationM: 201,
      surfaceElevationFt: 660,
      maxDepthM: 39.6,
      maxDepthFt: 130.0,
      meanDepthM: 12.0,
      meanDepthFt: 39.4,
      areaAcres: 54000,
      perimeterKm: 1850.0,
      geologicalOrigin: 'Massive impounded reservoir meandering along the historic Osage River within karst limestone bluffs',
      description: 'Known as "The Magic Dragon" for its serpentine shape meandering through deeply incised limestone bluffs, caves, and forested ravines.',
      bounds: {
        minLat: 38.120,
        maxLat: 38.260,
        minLon: -92.750,
        maxLon: -92.520,
      },
    },
    shape: {
      type: 'reservoir',
      aspectRatio: 1.5,
      lakeRadiusRatio: 0.38,
      rotationDeg: -35,
      bays: [
        { angleDeg: 40, distance: 0.42, radius: 0.18, depthMult: 0.7 },
        { angleDeg: 140, distance: 0.45, radius: 0.19, depthMult: 0.8 },
        { angleDeg: 220, distance: 0.38, radius: 0.17, depthMult: 0.75 },
      ],
      deepestPointOffset: { x: 0.2, y: -0.15 },
      shorelineRoughness: 0.14,
    },
    terrainProfile: {
      moraineHeightM: 70,
      roughness: 0.7,
      surroundingSlope: 'steep_bluffs',
    },
  },
  {
    metadata: {
      id: 'lake-maxinkuckee-in',
      name: 'Lake Maxinkuckee',
      state: 'Indiana',
      county: 'Marshall County',
      lat: 41.2014,
      lon: -86.4172,
      surfaceElevationM: 223,
      surfaceElevationFt: 732,
      maxDepthM: 26.8,
      maxDepthFt: 88.0,
      meanDepthM: 7.3,
      meanDepthFt: 24.0,
      areaAcres: 1864,
      perimeterKm: 15.6,
      geologicalOrigin: 'Glacial kettle basin shaped by multiple melting ice blocks during the Wisconsin glaciation',
      description: 'Second largest natural lake in Indiana, famous for the Culver Academies shoreline, kettle holes, and submerged kettle ridges.',
      bounds: {
        minLat: 41.175,
        maxLat: 41.228,
        minLon: -86.445,
        maxLon: -86.388,
      },
    },
    shape: {
      type: 'kettle',
      aspectRatio: 1.1,
      lakeRadiusRatio: 0.39,
      rotationDeg: 15,
      bays: [
        { angleDeg: 60, distance: 0.35, radius: 0.16, depthMult: 0.7 },
        { angleDeg: 200, distance: 0.32, radius: 0.15, depthMult: 0.6 },
      ],
      deepestPointOffset: { x: -0.05, y: -0.1 },
      shorelineRoughness: 0.06,
    },
    terrainProfile: {
      moraineHeightM: 25,
      roughness: 0.45,
      surroundingSlope: 'glacial_till',
    },
  },
  {
    metadata: {
      id: 'lake-minnetonka-mn',
      name: 'Lake Minnetonka',
      state: 'Minnesota',
      county: 'Hennepin County',
      lat: 44.9300,
      lon: -93.6200,
      surfaceElevationM: 283,
      surfaceElevationFt: 928,
      maxDepthM: 34.4,
      maxDepthFt: 113.0,
      meanDepthM: 9.1,
      meanDepthFt: 30.0,
      areaAcres: 14528,
      perimeterKm: 201.0,
      geologicalOrigin: 'Complex network of glacial kettle depressions and tunnel valley channels formed under ice sheet',
      description: 'An intricate labyrinth of over 23 distinct named bays, glacial moraine islands, channels, and sudden deep kettle holes (such as Crystal Bay).',
      bounds: {
        minLat: 44.880,
        maxLat: 44.980,
        minLon: -93.720,
        maxLon: -93.520,
      },
    },
    shape: {
      type: 'complex_bays',
      aspectRatio: 1.3,
      lakeRadiusRatio: 0.43,
      rotationDeg: -20,
      bays: [
        { angleDeg: 35, distance: 0.45, radius: 0.22, depthMult: 0.8 },
        { angleDeg: 110, distance: 0.42, radius: 0.20, depthMult: 0.7 },
        { angleDeg: 210, distance: 0.40, radius: 0.23, depthMult: 0.9 },
        { angleDeg: 290, distance: 0.43, radius: 0.19, depthMult: 0.75 },
      ],
      islands: [
        { x: -0.05, y: 0.05, radius: 0.06 },
        { x: 0.15, y: -0.1, radius: 0.04 },
      ],
      deepestPointOffset: { x: -0.15, y: 0.12 },
      shorelineRoughness: 0.12,
    },
    terrainProfile: {
      moraineHeightM: 28,
      roughness: 0.52,
      surroundingSlope: 'glacial_till',
    },
  },
];
